# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net
name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  SERVER_APP_NAME: "filewatch-dev"
  

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0
        
    - name: Restore dependencies
      run: dotnet restore
      
    - name: Build
      run: dotnet build --no-restore
    
    
    - name: Publish
      run: dotnet publish

     # - names: test with dotnet
    #  run: dotnet test --no restore ...
    # - name: upload dotnet-results 
    #  uses: actions/upload-artifact@v4

    
  # deploy: 
  #    runs-on: windows-latest
  #    needs: build

  #    steps: 
  #    - name: Deploy to Azure nonprod
  #    - uses: azure/webapps-deploy@v2
  #      with:
  #        app-name:  ${{env.SERVER-APP-NAME}}
  #        publish_profle: ${{secrets.SERVER-PUBLISH-PROFILE}}
  #        package: ./publish

  #   steps: 
  #     - name: Downlaod artifact from build job
  #       uses: actions/download-artifact@v4
  #       with:
  #         name: .net-app

  #     - name: Deploy to ?
  #       id:
  #       uses:
  #         with:

  # deploy to production:
